name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-15-intel, macos-latest, ubuntu-latest]
    defaults:
      run:
        shell: ${{ matrix.os == 'windows-latest' && 'msys2 {0}' || 'bash' }}
    steps:
      - uses: actions/checkout@v6
      - name: Setup Ubuntu Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install -y meson ninja-build libglib2.0-dev \
                                  gobject-introspection libgirepository1.0-dev \
                                  python3-pip
          pip3 install gi-docgen
      - name: Setup macOS Dependencies
        if: startsWith(matrix.os, 'macos-')
        run: brew install meson ninja glib gobject-introspection
      - name: Setup Windows (MSYS2/UCRT64)
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-meson
            mingw-w64-ucrt-x86_64-ninja
            mingw-w64-ucrt-x86_64-glib2
      - name: Build
        run: |
          meson setup _build -Dprofile=development \
                             -Ddocumentation=${{ matrix.os == 'ubuntu-latest' }}
          ninja -C _build
      - name: Run Tests
        run: |
          ninja -C _build test
      - name: Generate Documentation
        if: matrix.os == 'ubuntu-latest'
        run: ninja -C _build doc
      - name: Upload Docs Artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-pages-artifact@v3
        with:
          path: _build/docgen/
      - name: Deploy to GitHub Pages
        if: matrix.os == 'ubuntu-latest'
        id: deployment
        uses: actions/deploy-pages@v4
